//LOCALHOST
### Get all contacts

GET  http://localhost:3000/contacts

### Get contact by Id
GET  http://localhost:3000/contacts/67ce54a5ea38de1ce10ebcd6
### Get contact by Id
GET  http://localhost:3000/contacts/67ce5520ea38de1ce10ebcd7
### Get contact by Id
GET  http://localhost:3000/contacts/67ce54a5ea38de1ce10ebcd8

//RENDER
### Get all contacts
GET https://project1-0we1.onrender.com/contacts


// RENDER
### Get contact by Id
GET https://project1-0we1.onrender.com/contacts/67ce54a5ea38de1ce10ebcd6
### Get contact by Id
GET https://project1-0we1.onrender.com/contacts/67ce54a5ea38de1ce10ebcd7
### Get contact by Id
GET https://project1-0we1.onrender.com/contacts/67ce54a5ea38de1ce10ebcd8